ingress:
  hostname: chemscraper.backend.localhost
  tls: false
  annotations: {}

controller:
  images: 
    yolo: dprl/yolov8server:latest
    symbolscraper: dprl/symbolscraper-server:latest
    chemscraper: dprl/chemscraper:latest

    # LEGACY IMAGE NAME
    #yolo: dprl/yoloserver:latest
  

# TODO: config for GPU support
    #deploy:
    #  resources:
    #    reservations:
    #      devices
    #        - driver: nvidia
    #          capabilities: [gpu]


