ingress:
  hostname: chemscraper.backend.localhost
  tls: false
  annotations: {}

config:
  enableGPU: false

controller:
  imagePullPolicy: Always
  images: 
    yolo: dprl/yolov8server:latest
    symbolscraper: dprl/symbolscraper-server:latest
    chemscraper: dprl/chemscraper:v0.1-icdar2024

    # DEV IMAGE NAMES
    #chemscraper: dprl/chemscraper:staging

    # USTABLE IMAGE NAMES
    #chemscraper: dprl/chemscraper:latest

    # LEGACY IMAGE NAMES
    #yolo: dprl/yoloserver:latest
    #chemscraper: dprl/chemscraper:json
  

# TODO: config for GPU support
    #deploy:
    #  resources:
    #    reservations:
    #      devices
    #        - driver: nvidia
    #          capabilities: [gpu]


