ingress:
  hostname: chemscraper.backend.localhost
  tls: false
  annotations: {}

config:
  enableGPU: false

controller:
  imagePullPolicy: Always
  images: 
    yolo: dprl/yolov8server:latest
    symbolscraper: dprl/symbolscraper-server:latest
    chemscraper: dprl/chemscraper:dev_v0.4.0
    lgap: dprl/lgap:latest
    reactionminer_search: dprl/reactionminer_search:dev
    chemdataextractorapi: sprl/chemdataextractorapi:dev

    #chemscraper: dprl/chemscraper:staging_v0.2.1

    # DEV IMAGE NAMES
    #chemscraper: dprl/chemscraper:staging

    # UNSTABLE IMAGE NAMES
    #chemscraper: dprl/chemscraper:latest

    # LEGACY IMAGE NAMES
    #yolo: dprl/yoloserver:latest
    #chemscraper: dprl/chemscraper:json
  



